#------------------------------------------------------------------------------
# written by: mcdaniel
# date: june-2022
#
# usage: top-level workflow. Initiated manually from Github Actions console page
#        Builds all Docker containers.
#------------------------------------------------------------------------------
name: Build openedx container

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: {{ cookiecutter.global_aws_region }}
      NAMESPACE: {{ cookiecutter.global_platform_name }}-{{ cookiecutter.global_platform_region }}-{{ cookiecutter.environment_name }}
      EKS_CLUSTER_NAME: {{ cookiecutter.global_platform_name }}-{{ cookiecutter.global_platform_region }}-{{ cookiecutter.global_platform_shared_resource_identifier }}

      CUSTOM_THEME_REPOSITORY: {{ cookiecutter.ci_build_theme_repository }}
      CUSTOM_THEME_REPOSITORY_ORGANIZATION: {{ cookiecutter.ci_build_theme_repository_organization }}
      CUSTOM_THEME_REPOSITORY_REF: {{ cookiecutter.ci_build_theme_ref }}

    steps:
      - uses: actions/checkout@{{ cookiecutter.ci_actions_checkout_version }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@{{ cookiecutter.ci_actions_configure_aws_credentials_version }}
        with:
          aws-access-key-id: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID }}{% endraw %}
          aws-secret-access-key: {% raw %}${{ secrets.AWS_SECRET_ACCESS_KEY }}{% endraw %}
          aws-region: {% raw %}${{ env.AWS_REGION }}{% endraw %}

      #------------------------------------------------------------------------
      # install and configure tutor
      #------------------------------------------------------------------------
      - name: Initialize environment
        uses: openedx-actions/tutor-k8s-init@{{ cookiecutter.ci_openedx_actions_tutor_k8s_init_version }}
        with:
          eks-namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}
          eks-cluster-name: {% raw %}${{ env.EKS_CLUSTER_NAME }}{% endraw %}
          aws-region: {% raw %}${{ env.AWS_REGION }}{% endraw %}
          tutor-version: "{{ cookiecutter.ci_build_tutor_version }}"

      #------------------------------------------------------------------------
      # Add a custom theme here.
      #------------------------------------------------------------------------
      - name: Add a custom theme
        uses: openedx-actions/tutor-plugin-build-openedx-add-theme@{{ cookiecutter.ci_openedx_actions_tutor_plugin_build_openedx_add_theme_version }}
        with:
          repository: {% raw %}${{ env.CUSTOM_THEME_REPOSITORY }}{% endraw %}
          repository-organization: {% raw %}${{ env.CUSTOM_THEME_REPOSITORY_ORGANIZATION }}{% endraw %}
          repository-ref: {% raw %}${{ env.CUSTOM_THEME_REPOSITORY_REF }}{% endraw %}
          # UN-COMMENT THIS IF YOUR REPO IS PRIVATE.
          #----------------------------------------------
          #repository-token: {% raw %}${{ secrets.PAT }}{% endraw %}
          #----------------------------------------------

      #------------------------------------------------------------------------
      # Add any Python requirements here.
      # These include:
      # - generic Python PyPi packages
      # - Xblocks
      # - Open edX Plugin(s)
      # - your own custom repos
      #
      # note that `repository-token` is optional and is only needed for
      # private repositories
      #------------------------------------------------------------------------
      - name: Add an edx plugin
        uses: openedx-actions/tutor-plugin-build-openedx-add-requirement@{{ cookiecutter.ci_openedx_actions_tutor_plugin_build_openedx_add_requirement_version }}
        with:
          repository: openedx-plugin-example
          repository-organization: lpm0073
          repository-ref: main
          # UN-COMMENT THIS IF YOUR REPO IS PRIVATE.
          #----------------------------------------------
          #repository-token: {% raw %}${{ secrets.PAT }}{% endraw %}
          #----------------------------------------------

      - name: Add an Xblock
        uses: openedx-actions/tutor-plugin-build-openedx-add-requirement@{{ cookiecutter.ci_openedx_actions_tutor_plugin_build_openedx_add_requirement_version }}
        with:
          repository: edx-ora2
          repository-organization: openedx
          repository-ref: master
          # UN-COMMENT THIS IF YOUR REPO IS PRIVATE.
          #----------------------------------------------
          #repository-token: {% raw %}${{ secrets.PAT }}{% endraw %}
          #----------------------------------------------

      - name: Dump tutor config
        uses: openedx-actions/tutor-print-dump@{{ cookiecutter.ci_openedx_actions_tutor_print_dump }}

      #------------------------------------------------------------------------
      # Build and upload the Docker container
      #------------------------------------------------------------------------
      - name: Build openedx
        uses: openedx-actions/tutor-plugin-build-openedx@{{ cookiecutter.ci_openedx_actions_tutor_plugin_build_openedx_version }}
