#------------------------------------------------------------------------------
# written by: mcdaniel
# date: june-2022
#
# usage: top-level workflow. Initiated manually from Github Actions console page
#        Deploys a Tutor-created openedx Docker image to the Kubernetes cluster.
#------------------------------------------------------------------------------
name: Deploy {{ cookiecutter.global_platform_name }} {{ cookiecutter.environment_name }}

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # common settings
      # --------------------------------------------
      DEBUG_MODE: false
      AWS_REGION: {{ cookiecutter.global_aws_region }}

      # environment settings
      # --------------------------------------------
      ENVIRONMENT_ID: {{ cookiecutter.environment_name }}
      NAMESPACE: {{ cookiecutter.global_platform_name }}-{{ cookiecutter.global_platform_region }}-{{ cookiecutter.environment_name }}
      EKS_CLUSTER_NAME: {{ cookiecutter.global_platform_name }}-{{ cookiecutter.global_platform_region }}-{{ cookiecutter.global_platform_shared_resource_identifier }}
      S3_BUCKET_PREFIX: {{ cookiecutter.global_platform_name }}-{{ cookiecutter.global_platform_region }}-{{ cookiecutter.environment_name }}

      # feature flags for optional tutor modules
      # --------------------------------------------
      ENABLE_S3: true
      ENABLE_BACKUP: false
      {% if cookiecutter.ci_deploy_install_credentials_server == "Y" -%}
      ENABLE_CREDENTIALS: true
      {% else -%}
      ENABLE_CREDENTIALS: false
      {% endif -%}
      {% if cookiecutter.ci_deploy_install_discovery_service == "Y" %}
      ENABLE_DISCOVERY: true
      {% else -%}
      ENABLE_DISCOVERY: false
      {% endif -%}
      {% if cookiecutter.ci_deploy_install_ecommerce_service == "Y" %}
      ENABLE_ECOMMERCE: true
      {% else -%}
      ENABLE_ECOMMERCE: false
      {% endif -%}
      {% if cookiecutter.ci_deploy_install_forum_service == "Y" %}
      ENABLE_FORUM: true
      {% else -%}
      ENABLE_FORUM: false
      {% endif -%}
      {% if cookiecutter.ci_deploy_install_mfe_service == "Y" -%}
      ENABLE_MFE: true
      {% else -%}
      ENABLE_MFE: false
      {% endif -%}
      {% if cookiecutter.ci_deploy_install_notes_service == "Y" -%}
      ENABLE_NOTES: true
      {% else -%}
      ENABLE_NOTES: false
      {% endif -%}
      {% if cookiecutter.ci_deploy_install_xqueue_service == "Y" -%}
      ENABLE_XQUEUE: true
      {% else -%}
      ENABLE_XQUEUE: false
      {% endif -%}
      {% if cookiecutter.ci_deploy_install_license_manager_service == "Y" -%}
      ENABLE_LICENSE_MANAGER: true
      {% else %}
      ENABLE_LICENSE_MANAGER: false
      {% endif %}

    # deployment workflow begins here
    # --------------------------------------------
    steps:
      # checkout github repos: this repo, plus, all Gihubs Actions repos in this workflow
      - name: Checkout
        uses: actions/checkout@{{ cookiecutter.ci_actions_checkout_version }}

      # AWS helper method. creates a session token that's usable by all other
      # aws-actions. Prevents us from having to explicitly provide authentication credentials
      # to each aws-actions method individually.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@{{ cookiecutter.ci_actions_configure_aws_credentials_version }}
        with:
          aws-access-key-id: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID }}{% endraw %}
          aws-secret-access-key: {% raw %}${{ secrets.AWS_SECRET_ACCESS_KEY }}{% endraw %}
          aws-region: {% raw %}${{ env.AWS_REGION }}{% endraw %}

      # Open edX Github Actions init procedure. Provides reliable initializations of
      # kubectl, aws-cli and tutor
      - name: Initialize environment
        uses: openedx-actions/tutor-k8s-init@{{ cookiecutter.ci_openedx_actions_tutor_k8s_init_version }}
        with:
          eks-namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}
          eks-cluster-name: {% raw %}${{ env.EKS_CLUSTER_NAME }}{% endraw %}
          aws-region: {% raw %}${{ env.AWS_REGION }}{% endraw %}
          tutor-version: "{{ cookiecutter.ci_build_tutor_version }}"

      # Setup a connection to our AWS Elastic Container Registry so that we can pull
      # containers that we created with the build workflows in this Cookiecutter.
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@{{ cookiecutter.ci_actions_amazon_ecr_login_version }}

      # ---------------------------------------------------------------------------------
      # initialize workflow environment variables
      # ---------------------------------------------------------------------------------
      - name: Intialize AWS_ECR_URI
        shell: bash
        run: |-
          echo "AWS_ECR_URI={% raw %}${{ steps.login-ecr.outputs.registry }}{% endraw %}" >> $GITHUB_ENV

      - name: Intialize AWS ECR repo URIs
        shell: bash
        run: |-
          echo "AWS_ECR_REPOSITORY_BACKUP=${AWS_ECR_URI}/openedx_backup:latest" >> $GITHUB_ENV
          echo "AWS_ECR_REPOSITORY_CREDENTIALS=${AWS_ECR_URI}/openedx_credentials:latest" >> $GITHUB_ENV
          echo "AWS_ECR_REPOSITORY_LICENSE_MANAGER=${AWS_ECR_URI}/license_manager:latest" >> $GITHUB_ENV
          echo "AWS_ECR_REPOSITORY_MFE=${AWS_ECR_URI}/openedx_mfe:latest" >> $GITHUB_ENV
          echo "AWS_ECR_REPOSITORY_OPENEDX=${AWS_ECR_URI}/openedx:latest" >> $GITHUB_ENV

      - name: Load environment specific settings (direct)
        shell: bash
        run: |-
          # Pin the instalation ID with the Kubernetes namespace. It needs to be unique and static per instalation.
          cat ci/tutor-deploy/environments/{% raw %}${{ env.ENVIRONMENT_ID }}{% endraw %}/config.yml >> $GITHUB_ENV

      # note that values like $LMS_HOSTNAME come from this repo
      # in /ci/tutor-deploy/environments/{{ cookiecutter.environment_name }}/config.yml
      - name: Load additional environment specific settings
        shell: bash
        run: |-
          echo "TUTOR_LMS_HOST=$LMS_HOSTNAME" >> $GITHUB_ENV
          echo "TUTOR_CMS_HOST=$CMS_HOSTNAME" >> $GITHUB_ENV
          echo "TUTOR_DOCKER_IMAGE_OPENEDX=${AWS_ECR_REPOSITORY_OPENEDX}" >> $GITHUB_ENV
          echo "OPENEDX_COMMON_VERSION=open-release/{{ cookiecutter.ci_deploy_open_edx_version }}" >> $GITHUB_ENV

      # ---------------------------------------------------------------------------------
      # Configure optional tutor plugins
      # ---------------------------------------------------------------------------------
      - name: Enable tutor plugin - S3
        uses: openedx-actions/tutor-plugin-enable-s3@{{ cookiecutter.ci_openedx_actions_tutor_plugin_enable_s3_version }}
        if: {% raw %}${{ env.ENABLE_S3 == 'true' }}{% endraw %}
        with:
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}

      - name: Enable tutor plugin - Backup
        uses: openedx-actions/tutor-plugin-enable-backup@{{ cookiecutter.ci_openedx_actions_tutor_plugin_enable_backup_version }}
        if: {% raw %}${{ env.ENABLE_BACKUP == 'true' }}{% endraw %}
        with:
          aws-ecr-uri: ${AWS_ECR_REPOSITORY_BACKUPS}
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}

      - name: Enable tutor plugin - Discovery
        uses: openedx-actions/tutor-plugin-enable-discovery@{{ cookiecutter.ci_openedx_actions_tutor_plugin_enable_discovery_version }}
        if: {% raw %}${{ env.ENABLE_DISCOVERY == 'true' }}{% endraw %}
        with:
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}

      - name: Enable tutor plugin - MFE
        shell: bash
        run:  |-
          pip install tutor-mfe
          tutor plugins enable mfe
          tutor config save

      - name: Enable tutor plugin - Credentials
        uses: openedx-actions/tutor-plugin-enable-credentials@{{ cookiecutter.ci_openedx_actions_tutor_plugin_enable_credentials_version }}
        if: {% raw %}${{ env.ENABLE_CREDENTIALS == 'true' }}{% endraw %}
        with:
          version: {{ cookiecutter.ci_deploy_tutor_plugin_credentials_version }}
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}
          aws-ecr-uri: ${AWS_ECR_REPOSITORY_CREDENTIALS}
          common-logo-url: {{ cookiecutter.global_platform_logo_url }}

      - name: Enable tutor plugin - Xqueue
        uses: openedx-actions/tutor-plugin-enable-xqueue@{{ cookiecutter.ci_openedx_actions_tutor_plugin_enable_xqueue_version }}
        if: {% raw %}${{ env.ENABLE_XQUEUE == 'true' }}{% endraw %}
        with:
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}

      - name: Enable tutor plugin - Notes
        uses: openedx-actions/tutor-plugin-enable-notes@{{ cookiecutter.ci_openedx_actions_tutor_plugin_enable_notes_version }}
        if: {% raw %}${{ env.ENABLE_NOTES == 'true' }}{% endraw %}
        with:
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}

      - name: Enable tutor plugin - Ecommerce
        uses: openedx-actions/tutor-plugin-enable-ecommerce@{{ cookiecutter.ci_openedx_actions_tutor_plugin_enable_ecommerce_version }}
        if: {% raw %}${{ env.ENABLE_ECOMMERCE == 'true' }}{% endraw %}
        with:
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}
          secrets-s3-bucket-name: {% raw %}${{ env.S3_BUCKET_PREFIX }}{% endraw %}-secrets
          currency: USD
          enabled-payment-processors: '["stripe", "paypal"]'

      - name: Enable tutor plugin - Forum
        uses: openedx-actions/tutor-plugin-enable-forum@{{ cookiecutter.ci_openedx_actions_tutor_plugin_enable_forum_version }}
        if: {% raw %}${{ env.ENABLE_FORUM == 'true' }}{% endraw %}

      - name: Enable tutor plugin - License Manager
        uses: openedx-actions/tutor-enable-plugin-license-manager@{{ cookiecutter.ci_openedx_actions_tutor_plugin_enable_license_manager_version }}
        if: {% raw %}${{ env.ENABLE_LICENSE_MANAGER == 'true' }}{% endraw %}
        with:
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}
          aws-ecr-uri: ${AWS_ECR_REPOSITORY_LICENSE_MANAGER}
          host: subscriptions.{{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}
          lms_host: {{ cookiecutter.environment_subdomain }}.{{ cookiecutter.global_root_domain }}

      # ---------------------------------------------------------------------------------
      # Configure backend services
      # ---------------------------------------------------------------------------------
      - name: Configure SMTP
        uses: openedx-actions/tutor-k8s-configure-smtp@{{ cookiecutter.ci_openedx_actions_tutor_k8s_configure_smtp_version }}
        with:
          aws-ses-iam-key: {% raw %}${{ secrets.AWS_SES_IAM_KEY }}{% endraw %}
          aws-ses-iam-secret: {% raw %}${{ secrets.AWS_SES_IAM_SECRET }}{% endraw %}
          aws-region: {% raw %}${{ env.AWS_REGION }}{% endraw %}

      - name: Configure Redis
        uses: openedx-actions/tutor-k8s-configure-redis@{{ cookiecutter.ci_openedx_actions_tutor_k8s_configure_redis_version }}
        with:
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}

      - name: Configure MySQL
        uses: openedx-actions/tutor-k8s-configure-mysql@{{ cookiecutter.ci_openedx_actions_tutor_k8s_configure_mysql_version }}
        with:
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}

      - name: Configure MongoDB
        uses: openedx-actions/tutor-k8s-configure-mongodb@{{ cookiecutter.ci_openedx_actions_tutor_k8s_configure_mongodb_version }}
        with:
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}
          {% if cookiecutter.stack_add_remote_mongodb == "Y" -%}
          remote-server: "true"
          {% elif cookiecutter.stack_add_remote_mongodb == "N" -%}
          remote-server: "false"
          {% endif %}

      # ---------------------------------------------------------------------------------
      # Configure application secrets
      # ---------------------------------------------------------------------------------
      - name: Fetch JWT token
        uses: openedx-actions/tutor-k8s-configure-jwt@{{ cookiecutter.ci_openedx_actions_tutor_k8s_configure_jwt_version }}
        with:
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}


      # see: https://github.com/{{ cookiecutter.github_account_name }}/openedx_devops/blob/main/terraform/modules/kubernetes_secrets/main.tf
      - name: Configure edx secret
        uses: openedx-actions/tutor-k8s-configure-edx-secret@{{ cookiecutter.ci_openedx_actions_tutor_k8s_configure_edx_secret_version }}
        with:
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}

      # ---------------------------------------------------------------------------------
      # Add your custom configuration tasks here ....
      # ---------------------------------------------------------------------------------
      - name: Disable Caddy web proxy service
        shell: bash
        run:  |-
          tutor config save --set ENABLE_WEB_PROXY=false

      - name: Disable LMS courseware micro front-end app
        uses: openedx-actions/tutor-plugin-configure-courseware-mfe@{{ cookiecutter.ci_openedx_actions_tutor_plugin_configure_courseware_mfe_version }}
        with:
          enabled: 'false'

      - name: Disable Caddy web proxy service
        shell: bash
        run:  |-
          tutor config save --set ENABLE_WEB_PROXY=false

      # see: https://github.com/overhangio/tutor-mfe
      - name: Disable all MFEs
        shell: bash
        run: |-
          tutor config save --set MFE_ACCOUNT_MFE_APP=null \
                            --set MFE_GRADEBOOK_MFE_APP=null \
                            --set MFE_PROFILE_MFE_APP=null \
                            --set MFE_COURSE_AUTHORING_MFE_APP=null \
                            --set MFE_DISCUSSIONS_MFE_APP=null \
                            --set MFE_AUTHN_MFE_APP=null \

      - name: Dump tutor config
        uses: openedx-actions/tutor-print-dump@{{ cookiecutter.ci_openedx_actions_tutor_print_dump }}

      # ---------------------------------------------------------------------------------
      # Deploy
      # ---------------------------------------------------------------------------------
      - name: Add tutor k8s-specific deployment tasks
        uses: openedx-actions/tutor-plugin-enable-k8s-deploy-tasks@{{ cookiecutter.ci_openedx_actions_tutor_plugin_enable_k8s_deploy_tasks_version }}

      - name: Deploy to Kubernetes
        uses: ./.github/actions/tutor/k8s/deploy
        with:
          environment-id: {% raw %}${{ env.ENVIRONMENT_ID }}{% endraw %}
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}

      - name: Set theme
        shell: bash
        run:  |-
          tutor k8s do settheme edx-theme

      - name: Create admin user
        uses: openedx-actions/tutor-k8s-configure-edx-admin@{{ cookiecutter.ci_openedx_actions_tutor_k8s_configure_edx_admin }}
        with:
          namespace: {% raw %}${{ env.NAMESPACE }}{% endraw %}

      - name: Summary
        shell: bash
        run: kubectl get hpa
