#------------------------------------------------------------------------------
# written by: Miguel Afonso
#             https://www.linkedin.com/in/mmafonso/
#
# date: Aug-2021
#
# usage: setup SSL certs for EKS load balancer worker node instances.
#        see https://cert-manager.io/docs/
#------------------------------------------------------------------------------
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
spec:
  secretName: wild-openedx-prod-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  commonName: courses.tutorlabs.cloud
  dnsNames:
    - "*.courses.tutorlabs.cloud"
