#------------------------------------------------------------------------------
# written by: Miguel Afonso
#             https://www.linkedin.com/in/mmafonso/
#
# date: Aug-2021
#
# usage: setup SSL certs for EKS load balancer worker node instances.
#        see https://cert-manager.io/docs/
#------------------------------------------------------------------------------
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
  namespace: tutorlabs-global-prod
spec:
  acme:
    email: no-reply@tutorlabs.cloud
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          # NOTE: make sure that this is the hosted Zone ID for
          # for the environment domain.
          route53:
            region: eu-west-2
            hostedZoneID: Z0025202252VR1DHZSK9
